# Generated by Django 5.1.4 on 2025-01-05 01:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moldes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Nombre')),
                ('lenght', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Largo')),
                ('wide', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Ancho')),
                ('height', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Altura')),
                ('diameter', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Diametro')),
                ('superior_diameter', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Diametro superior')),
                ('inferior_diameter', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Diametro inferior')),
                ('material', models.CharField(choices=[('INOX_04', 'Inox 0.4mm'), ('INOX_05', 'Inox 0.5mm'), ('INOX_06', 'Inox 0.6mm'), ('ALUM_04', 'Alum 0.4mm'), ('ALUM_07', 'Alum 0.7mm')], default='INOX_04', max_length=15, verbose_name='Material')),
            ],
        ),
    ]
