# Generated by Django 4.2.11 on 2025-02-11 04:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moldes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('cellphone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('bussiness', models.CharField(blank=True, max_length=100, null=True, verbose_name='Negocio')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Nombre')),
                ('description', models.TextField(blank=True)),
                ('length', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Largo')),
                ('wide', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Ancho')),
                ('height', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Altura')),
                ('diameter', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Diametro')),
                ('superior_diameter', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Diametro superior')),
                ('inferior_diameter', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Diametro inferior')),
                ('material', models.CharField(choices=[('INOX_04', 'Inox 0.4mm'), ('INOX_05', 'Inox 0.5mm'), ('INOX_06', 'Inox 0.6mm'), ('ALUM_04', 'Alum 0.4mm'), ('ALUM_07', 'Alum 0.7mm'), ('TOL_04', 'Tol 0.4mm')], default='INOX_04', max_length=15, verbose_name='Material')),
                ('shows_in_catalog', models.BooleanField(default=False, verbose_name='¿Mostrar en catalogo publico?')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='moldes.category')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateTimeField()),
                ('sale_status', models.CharField(choices=[('FABRICAR', 'Por Fabricar'), ('STOCK', 'Listo para Entregar'), ('ENTREGADO', 'Entregado Por Cobrar'), ('SOLO_COBRADO', 'Solo Cobrado'), ('COBRADO_ENTREGADO', 'Entregado y Cobrado')], default='FABRICAR', max_length=18, verbose_name='Estado de la Venta')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='moldes.client')),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('unitary_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='moldes.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='moldes.sale')),
            ],
        ),
        migrations.DeleteModel(
            name='Moldes',
        ),
    ]
