# Generated by Django 4.2.11 on 2025-02-13 23:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moldes', '0003_purchase_purchaseitem_remove_saleitem_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='sale_status',
            new_name='purchase_status',
        ),
        migrations.AlterField(
            model_name='product',
            name='diameter',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Diametro'),
        ),
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Altura'),
        ),
        migrations.AlterField(
            model_name='product',
            name='inferior_diameter',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Diametro inferior'),
        ),
        migrations.AlterField(
            model_name='product',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Largo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='superior_diameter',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Diametro superior'),
        ),
        migrations.AlterField(
            model_name='product',
            name='wide',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Ancho'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='moldes.purchase'),
        ),
    ]
