# Generated by Django 4.2.11 on 2025-02-14 01:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moldes', '0004_rename_sale_status_purchase_purchase_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='diameter',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Diametro'),
        ),
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Altura'),
        ),
        migrations.AlterField(
            model_name='product',
            name='inferior_diameter',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Diametro inferior'),
        ),
        migrations.AlterField(
            model_name='product',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Largo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='superior_diameter',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Diametro superior'),
        ),
        migrations.AlterField(
            model_name='product',
            name='wide',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Ancho'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_status',
            field=models.CharField(choices=[('FABRICAR', 'Por Fabricar'), ('STOCK', 'En Stock'), ('ENTREGADO', 'Entregado Por Cobrar'), ('SOLO_COBRADO', 'Solo Cobrado'), ('COBRADO_ENTREGADO', 'Entregado y Cobrado')], default='FABRICAR', max_length=18, verbose_name='Estado de la Venta'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total de la compra'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='unitary_price',
            field=models.DecimalField(decimal_places=14, max_digits=18),
        ),
    ]
