# Generated by Django 4.2.11 on 2025-02-14 04:13

from django.db import migrations, models
import moldes.models


class Migration(migrations.Migration):

    dependencies = [
        ('moldes', '0006_remove_product_image_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=moldes.models.product_image_upload_path, verbose_name='Imagen del producto'),
        ),
    ]
