# Generated by Django 4.2.11 on 2025-02-14 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moldes', '0007_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='moldes.category'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='unitary_price',
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
    ]
