# Generated by Django 4.2.11 on 2025-02-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moldes', '0008_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='shows_in_home',
            field=models.BooleanField(default=False, verbose_name='¿Mostrar categoria en home?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(choices=[('INOX_04', 'Acero Inoxidable 0.4mm de espesor'), ('INOX_05', 'Acero Inoxidable 0.5mm de espesor'), ('INOX_06', 'Acero Inoxidable 0.6mm de espesor'), ('ALUM_04', 'Aluminio 0.4mm de espesor'), ('ALUM_07', 'Aluminio 0.7mm de espesor'), ('TOL_04', 'Tol Galvanizado 0.4mm de espesor')], default='INOX_04', max_length=15, verbose_name='Material'),
        ),
    ]
