# Generated by Django 4.2.11 on 2025-02-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moldes', '0009_category_shows_in_home_alter_product_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchase_status',
            field=models.CharField(choices=[('FABRICAR', 'Por Fabricar'), ('STOCK', 'En Stock'), ('ENTREGADO', 'Entregado Por Cobrar'), ('SOLO_COBRADO', 'Solo Cobrado, No entregado'), ('COBRADO_ENTREGADO', 'Entregado y Cobrado')], default='FABRICAR', max_length=18, verbose_name='Estado de la Venta'),
        ),
    ]
