# Generated by Django 5.1.4 on 2025-02-15 11:18

import moldes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moldes', '0010_alter_purchase_purchase_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to=moldes.models.upload_to_category, verbose_name='Imagen de la Categoría'),
        ),
    ]
